### ISSUE TITLE
possible error with harmony

### ISSUE THREAD

**Issue by poulpoulsen** [squinkylabs/SqHarmony#14]
hello,
i noticed the following trace in log.txt, if i leave rack.
additionally the modul scalecv from aaron static displays garbled text, if i load harmony. strange :-(
unfortunately i am not a developer, but perhaps it is something with tonecarver also.
i have started an older version of the patch also with tonecarver, but without harmony and it works.

any ideas?
i am on linux fedora 38 with newest rack version and newest harmony from github (2.2.0).

[22.950 info src/engine/Engine.cpp:1240 fromJson] Creating module Squinktronix Harmony 1
[22.958 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
11: ./Rack() [0x4042ed]
10: /lib64/libc.so.6(+0x3dbb0)
9: /home/held/.Rack2/plugins-lin-x64/Tonecarver/plugin.so(Blur::processFrame()+0x280)
8: /home/held/.Rack2/plugins-lin-x64/Tonecarver/plugin.so(Blur::process(rack::engine::Module::ProcessArgs const&)+0x913)
7: ./libRack.so(rack::engine::Module::doProcess(rack::engine::Module::ProcessArgs const&)+0x9dc)
6: ./libRack.so(rack::engine::Engine::stepBlock(int)+0x749)
5: ./libRack.so(rack::audio::Device::processBuffer(float const*, int, float*, int, int)+0x143)
4: ./libRack.so(rack::RtAudioDevice::rtAudioCallback(void*, void*, unsigned int, double, unsigned int, void*)+0xa3)
3: ./libRack.so(+0x79ee02)
2: ./libRack.so(+0x79f325)
1: /lib64/libc.so.6(+0x8c947)
0: /lib64/libc.so.6(+0x112860)

**Comment by poulpoulsen** [comment]
it seems, that the modul [Grande](https://library.vcvrack.com/?brand=Grande) [PolyMergeResplit](https://library.vcvrack.com/GrandeModular/PolyMergeResplit) is responsible for the garbling text in scalecv.
after removing it, it is gone.
will check if any other modul interfere with.

**Comment by squinkylabs** [comment]
Yes, there are a lot of bad modules out there. I had a scare like this a year and a half ago. Again, it was not me, but some other plugin.

I can't quite tell from the above, but it sounds like in the "bad" scenario you were crashing and in the "good" scenario everything is fine?

**Comment by poulpoulsen** [comment]
unfortunately the problem here laid in three faulty moduls. none of them are reported in a crash.
sorry for the noise.
now it is working: no crash and no scrumbled text.
your modules work also without a problem.
